Update CICD.yml

diff --git a/.github/workflows/CICD.yml b/.github/workflows/CICD.yml
--- a/.github/workflows/CICD.yml
+++ b/.github/workflows/CICD.yml
@@ -1,14 +1,11 @@
 name: CI
-
 on:
   push:
     branches: [ "main" ]
   pull_request:
     branches: [ "main" ]
-
 permissions:
   contents: read
-
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -19,18 +16,15 @@ jobs:
         with:
           java-version: '17'
           distribution: 'temurin'
-
       - name: Build with Maven
         run: |
           chmod 777 ./mvnw
           ./mvnw clean package -Dtestskip
-
       - name: Login to DockerHub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
-
       - name: Build Docker
         run: docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/live_server .
       - name: Push Docker
@@ -59,7 +53,18 @@ jobs:
             echo "STOPPED_PORT=8080" >> $GITHUB_ENV
             echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
           fi
- 
+
+      - name: Check Docker service and container status
+        uses: appleboy/ssh-action@master
+        with:
+          username: ubuntu
+          host: ${{ secrets.LIVE_SERVER_IP }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            sudo systemctl status docker || sudo systemctl restart docker
+            sudo docker ps -a
+            sudo docker images
+
       - name: Docker compose
         uses: appleboy/ssh-action@master
         with:
@@ -88,7 +93,7 @@ jobs:
           script: |
             sudo docker exec -i nginxserver bash -c 'echo "set \$service_url ${{ env.TARGET_UPSTREAM }};" > /etc/nginx/conf.d/service-env.inc && nginx -s reload' 
 
-      - name: Stop current server
+      - name: Stop and remove current server
         uses: appleboy/ssh-action@master
         with:
           username: ubuntu
@@ -96,5 +101,9 @@ jobs:
           key: ${{ secrets.EC2_SSH_KEY }}
           script_stop: true
           script: |
-            sudo docker stop ${{env.CURRENT_UPSTREAM}}
-            sudo docker rm ${{env.CURRENT_UPSTREAM}}
+            if sudo docker ps -a | grep -q ${{env.CURRENT_UPSTREAM}}; then
+              sudo docker stop ${{env.CURRENT_UPSTREAM}} || true
+              sudo docker rm ${{env.CURRENT_UPSTREAM}} || true
+            else
+              echo "Container '${{env.CURRENT_UPSTREAM}}' not found. Skipping stop and remove."
+            fi
